### ISSUE TITLE
[Suggest] http digest authentication multiple time fail

### ISSUE THREAD

**Issue by vmwell** [icholy/digest#1]
Thanks for your code, solved my proble.

But there is a problem，post the second url with Authorization header, it will be fail. because the server has given up the nonce paramter.

so I think post the second url with cookie header.

I modify the code:

1. add cookiejar.go file

``` go
type HttpCookieJar struct {
	cookies []*http.Cookie
}

func (jar *HttpCookieJar) SetCookies(u *url.URL, cookies []*http.Cookie) {
	jar.cookies = cookies
}
func (jar *HttpCookieJar) Cookies(u *url.URL) []*http.Cookie {
	return jar.cookies
}
```

2. modify transport.go file

``` go
func (t *Transport) clear(res *http.Response) error {
	host := res.Request.URL.Hostname()

	t.cacheMu.Lock()
	if t.cache == nil {
		t.cache = map[string]*cached{}
	}

	delete(t.cache, host)

	t.cacheMu.Unlock()

	return nil
}

func (t *Transport) RoundTrip(req *http.Request) (*http.Response, error) {
	// use the configured transport if there is one
	tr := t.Transport
	if tr == nil {
		tr = http.DefaultTransport
	}
	// don't modify the original request
	clone, err := cloner(req)
	if err != nil {
		return nil, err
	}
	// setup the first request
	first, err := clone()
	if err != nil {
		return nil, err
	}
	// try to authorize the request using a cached challenge
	if err := t.authorize(first); err != nil {
		return nil, err
	}
	// the first request will either succeed or return a 401
	res, err := tr.RoundTrip(first)
	if err != nil || res.StatusCode != http.StatusUnauthorized {
		return res, err
	}
	// close the first message body
	res.Body.Close()
	// save the challenge for future use
	if err := t.save(res); err != nil {
		return nil, err
	}
	// setup the second request
	second, err := clone()
	if err != nil {
		return nil, err
	}
	// authorise a second request based on the new challenge
	if err := t.authorize(second); err != nil {
		return nil, err
	}

	resp, error := tr.RoundTrip(second)

	t.clear(resp)

	return resp, error
}
```

3 Test demo

// Source code from https://github.com/icholy/digest

``` go
func TestHttpDigest(t *testing.T) {
	jar := new(HttpCookieJar)
	client := http.Client{
		Transport: &Transport{
			Username: "test",
			Password: "test",
		},
		Jar: jar,
	}

	res, _ := client.Get("http://localhost:8080/demo/user.action")
	println(res.Status)

	res, _ = client.Get("http://localhost:8080/demo/test.action")
	println(res.Status)
}
```

**Comment by icholy** [comment]
Please fix the code formatting in your issue: https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by icholy** [comment]
What error are you seeing?

**Comment by vmwell** [comment]
![微信图片_20200730150634](https://user-images.githubusercontent.com/4065604/88891776-4db67b00-d276-11ea-902d-ad4aaa50dc7a.png)

http client post the second url (http://localhost:8080/demo/test.action) with Authorization, the server will reject, because it is not safe. so must re-authenticate.

The cookiejar https://golang.org/pkg/net/http/cookiejar/ is very good.

**Comment by icholy** [comment]
That’s how digest with works. Wireshark your browser and you’ll see the same thing.

**Comment by vmwell** [comment]
Yes, I use spring security as server digest auth, I read spring securitysource code, the nonce validity second is 300 second.

Thanks.

**Comment by rolandjitsu** [comment]
I'm actually facing the same issue when the server is using [Flask](https://flask-httpauth.readthedocs.io/en/latest/). Same thing happens from Postman. The 2nd request fails unless I clear the cookie.

But doing a request from Go using this lib fails on first try too.

**Comment by icholy** [comment]
Please read the thread. It's not an issue, it's how digest auth works.

**Comment by rolandjitsu** [comment]
So it's expected not to work with the flash-auth digest impl.? Or you're only talking about the 2nd req fail?

**Comment by icholy** [comment]
The first request should always fail assuming the client doesn't have a cached challenge from a previous failed request. Some servers don't support re-using the challenge, so every other request will fail (to get the new challenge).

**Comment by icholy** [comment]
Copy/paste that into a new issue. This sounds like it might be a real bug.

**Comment by icholy** [comment]
@rolandjitsu the problem is that flask auth is trying to set cookies as part of the challenge response. That response never makes it out of the transport, so the `http.Client` doesn't have a chance to add it to its `http.(*Client),Jar`. I just pushed version `v0.1.11` which allows you to specify a `http.CookieJar` in the `digest.Transport`.

``` go
package main

import (
  "net/http"
  "net/http/cookiejar"

  "github.com/icholy/digest"
)

func main() {
  jar, _ := cookiejar.New(nil)
  client := &http.Client{
    Jar: jar,
    Transport: &digest.Transport{
      Jar: jar,
      Username: "foo",
      Password: "bar",
    },
  }
  res, err := client.Get("http://localhost:8080/some_outdated_service")
  if err != nil {
    panic(err)
  }
  defer res.Body.Close()
}
```

**Comment by rolandjitsu** [comment]
> @rolandjitsu the problem is that flask auth is trying to set cookies as part of the challenge response. That response never makes it out of the transport, so the `http.Client` doesn't have a chance to add it to its `http.(*Client).Jar`. I just pushed version `v0.1.11` which allows you to specify an `http.CookieJar` in the `digest.Transport`.

@icholy thanks!

**Comment by rolandjitsu** [comment]
@icholy just tested the fix and I can confirm it works.
